language: java
jdk:
- openjdk8

before_install:
- chmod +x gradlew

branches:
  only:
  - master

sudo: false
dist: trusty
addons:
  sonarcloud:
    organization: "isagiongo-github"
  token:
    secure: 8d56f33f537f93c28677e8ef04ef81439bf61959

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: ./gradlew sonarqube -Dsonar.projectKey=isagiongo_api-meetups-java-girls -Dsonar.organization=isagiongo-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=8d56f33f537f93c28677e8ef04ef81439bf61959
