language: java
jdk:
- openjdk8

before_install:
- chmod +x gradlew

branches:
  only:
  - master

sudo: false
dist: trusty
addons:
  sonarcloud:
    organization: "isagiongo-github"
  token:
    secure: c189457fac2b6991f231a7e82b8d5485500ef567

cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: ./gradlew sonarqube -Dsonar.projectKey=isagiongo_api-meetups-java-girls -Dsonar.organization=isagiongo-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c3f7b6bf7b53b4eed042e7bf91855c4b72f96e2e
